#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument.

# Requirements:

# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times

# Check if an IP address is provided as an argument
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Assign the argument to a variable
IP_ADDRESS="$1"

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"