#!/usr/bin/env bash
# Dispalys the sctive IPv4 addresses in the current system

# Run the following command in the docker terminal to install the 'ip' command:
# apt install iproute2

# ip -4 addr show | grep inet | cut -d ' ' -f 6 | cut -d'/' -f 1

# Unfortunately the check only wants us to use ifconfig
ifconfig | grep 'inet ' | awk '{print $2}'